## 분류 - knn============

- 가장 간단한 머신러닝 분류 학습 알고리즘

- 모델 관련 패턴 식이 없음 => 데이터마다 거리 계산

- 거리 기반 모델

- 하이퍼 파라미터 => k : 최근접 이웃 데이터 수

- 적용학습 : 회귀, 분류, 모두 가능

In [16]:
# 모듈 로딩------------------------------------------------------------------
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt

### KNN 이해하기

In [20]:
x=[[0],[1],[2],[3],[4]]
y=[0,0,1,1,1]

In [21]:
#KNN학습모델 객체 생성
knn=KNeighborsClassifier() #k=5 기본값

In [22]:
knn.fit(x,y)

KNeighborsClassifier()

In [23]:
# KNN 학습모델 객체 속성 확인
knn.classes_

array([0, 1])

In [24]:
knn.n_neighbors

5

In [27]:
# 예측
knn.predict(x)
knn.predict([[2.1]])

array([1])

In [28]:
knn.predict_proba([[2.1]])

array([[0.4, 0.6]])

In [29]:
knn.predict([[0.1]])

array([1])

In [30]:
knn.predict_proba([[0.1]])

array([[0.4, 0.6]])

In [31]:
# 평가===================================================
y_pre=knn.predict(x)

In [32]:
knn.score(x,y)

0.6

In [33]:
# 최적의 K 찾기
for _k in range(1,6):
    knn.n_neighbors=_k
    knn.fit(x,y)
    print(f"{_k} : {knn.score(x,y)}")

1 : 1.0
2 : 0.8
3 : 1.0
4 : 0.8
5 : 0.6


### [2] KNN 실습

* 데이터 : student_info.csv

* [2-1] 데이터 변환
    * 범주형 컬럼 추가 => 'tall', 'median', 'small'
    * 범주형 컬럼 추가 => bmi계산 후 '과체중', '정상', '저체중'
    * value <= 18.5 저체중
    * 18.5< value <= 23 정상
    * 23< <=25 과체중
    * 25< <=30 비만
    * 30< value 고도비만

In [34]:
file='./data/student_info.csv'

In [35]:
import pandas as pd

std_df=pd.read_csv(file)

In [36]:
std_df

no gender  weight_kg  height_cm
0    1      m         98        198
1    2      m         77        170
2    3      m         70        170
3    4      m         90        198
4    5      m         71        170
..  ..    ...        ...        ...
85  88      f        100        190
86  89      f         54        163
87  90      f         57        161
88  91      f        101        198
89  92      f        110        190

[90 rows x 4 columns]

In [37]:
std_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   no         90 non-null     int64 
 1   gender     90 non-null     object
 2   weight_kg  90 non-null     int64 
 3   height_cm  90 non-null     int64 
dtypes: int64(3), object(1)
memory usage: 2.9+ KB


In [39]:
std_df['height_cm'].median()

165.0

In [47]:
std_df['bmi']=std_df['weight_kg']/(std_df['height_cm']**2)*10000

In [48]:
std_df

no gender  weight_kg  height_cm        bmi
0    1      m         98        198  24.997449
1    2      m         77        170  26.643599
2    3      m         70        170  24.221453
3    4      m         90        198  22.956841
4    5      m         71        170  24.567474
..  ..    ...        ...        ...        ...
85  88      f        100        190  27.700831
86  89      f         54        163  20.324438
87  90      f         57        161  21.989892
88  91      f        101        198  25.762677
89  92      f        110        190  30.470914

[90 rows x 5 columns]

In [53]:
import numpy as np
# value <= 18.5 저체중
#     * 18.5< value <= 23 정상
#     * 23< <=25 과체중
#     * 25< <=30 비만
#     * 30< value 고도비만

ranges=[0,18.5,23,25,30,50]
std_df['bmi_label']=pd.cut(std_df['bmi'],ranges,labels=['저체중','정상','과체중','비만','고도비만'])





# np.where(std_df['bmi'] <=18.5 , 1)
# np.where(18.5< std_df['bmi'] <=23 , 2)
# np.where(23< std_df['bmi'] <=25 , 3)
# np.where(25< std_df['bmi'] <=30 , 4)
# np.where(std_df['bmi'] > 30 , 5)

In [54]:
std_df

no gender  weight_kg  height_cm        bmi bmi_label
0    1      m         98        198  24.997449       과체중
1    2      m         77        170  26.643599        비만
2    3      m         70        170  24.221453       과체중
3    4      m         90        198  22.956841        정상
4    5      m         71        170  24.567474       과체중
..  ..    ...        ...        ...        ...       ...
85  88      f        100        190  27.700831        비만
86  89      f         54        163  20.324438        정상
87  90      f         57        161  21.989892        정상
88  91      f        101        198  25.762677        비만
89  92      f        110        190  30.470914      고도비만

[90 rows x 6 columns]