### numpy 살펴보기

ndarray 객체 생성 및 속성들---------------------

[1]np.array()함수

In [1]:
import numpy as np

In [2]:
arr1=np.array([11,22,33])

In [5]:
arr2=np.array([1,"A",0.34])

In [8]:
arr3=np.array([[0,0,0],[0,0,0]])

In [13]:
# 0으로 원소값을 초기화 => np.zeros(shape)
arr4=np.zeros((28,28), dtype='int32')

In [16]:
#1로 모든 원소값을 초기화 => np.ones(shape)
arr5=np.ones((5,2))

In [17]:
type(arr5), arr5

(numpy.ndarray,
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]))

In [18]:
# 원하는 숫자로 모든 원소값 초기화=> np.full(shape, number)
arr6=np.full((2,3),255)

In [19]:
#연속된 범위 지정 원소값 초기화 => np.arange(시작, 종료, 간격)
arr7=np.arange(1,10,2)
arr7

array([1, 3, 5, 7, 9])

In [14]:
#type(arr2), arr2
# 다른 형태의 데이터도 자동으로 형변환 시켜서 어레이에 들어감

In [15]:
type(arr1), arr1, type(arr2), arr2, type(arr3), arr3, type(arr4), arr4

(numpy.ndarray,
 array([11, 22, 33]),
 numpy.ndarray,
 array(['1', 'A', '0.34'], dtype='<U32'),
 numpy.ndarray,
 array([[0, 0, 0],
        [0, 0, 0]]),
 numpy.ndarray,
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0],
        

[2] ndarray 객체 속성

In [4]:
arr1.shape,arr1.ndim,arr1.dtype

((3,), 1, dtype('int32'))

In [21]:
arr1=np.array([[2,2,2],[3,3,3]])
arr1

array([[2, 2, 2],
       [3, 3, 3]])

In [22]:
arr1.reshape(6)

array([2, 2, 2, 3, 3, 3])

In [23]:
arr1.reshape(-1)

array([2, 2, 2, 3, 3, 3])

In [24]:
arr1.reshape(-1,2)

array([[2, 2],
       [2, 3],
       [3, 3]])

In [29]:
#사이즈를 벗어나서 안됨
#arr1.reshape(-1,7)

In [34]:
# 안에 들어가 있는것을 보여줌
# flatten이랑 무슨차이인지 모르겟음
arr1.ravel()

array([2, 2, 2, 3, 3, 3])

In [32]:
# 차원을 펴서 보여주는 함수
# 원본은 안바뀜
arr1.flatten()

array([2, 2, 2, 3, 3, 3])