In [156]:
import sklearn
print(sklearn.__version__)

1.0.2


### [1]데이터 준비

In [157]:
# 필요한 모듈 로딩------------------------------------------
from sklearn.datasets import load_iris

In [158]:
iris=load_iris()

In [159]:
type(iris)

sklearn.utils.Bunch

In [160]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [161]:
# 속성정보 확인
for key, value in iris.items():
    print(f"[{key}]=>{value}")

[data]=>[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.

In [162]:
type(iris['data']),type(iris['target']),(iris['feature_names'])

(numpy.ndarray,
 numpy.ndarray,
 ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'])

In [163]:
# 판다스의 데이터프레임 또는 시리즈로 반환받기
iris, label=load_iris(return_X_y=True, as_frame=True)

In [164]:
type(iris), type(label)

(pandas.core.frame.DataFrame, pandas.core.series.Series)

### [2]학습용 데이터 + 테스트용 데이터 준비
-좋은 방법 : 두 종류 ~ 세 종류 데이터 따로 존재

-개선 방법 : 학습용 데이터를 분리해서 사용

-sklearn 제공 함수 : train_test_split()

In [165]:
import pandas as pd

In [166]:
iris.sample()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
12                4.8               3.0                1.4               0.1

In [167]:
from sklearn.model_selection import train_test_split

In [168]:
#입력=> 학습용 데이터, 학습용 라벨
#출력=> 학습용 데이터, 테스트용 데이터, 학습용 라벨, 테스트용 라벨 : 80%, 20%
X_train,X_test,y_train,y_test=train_test_split(iris,label, test_size=0.2)

In [169]:
len(X_train), len(X_test), len(y_train), len(y_test)

(120, 30, 120, 30)

In [170]:
#입력=> 학습용 데이터, 학습용 라벨
#출력=> 학습용 데이터, 검증용 데이터, 학습용 라벨, 검증용 라벨 : 80%, 20%
X_train,X_val,y_train,y_val=train_test_split(X_train,y_train, test_size=0.2)

In [171]:
len(X_train), len(X_val), len(y_train), len(y_val)

(96, 24, 96, 24)

### [3] 학습 모델 생성---------------------------------------

-데이터 구조 : 피쳐 + 라벨 => 지도학습

-라벨   타입 : 범주형      => 분류

-분류 학습 방법 선택 => 생성

In [172]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [173]:
# 학습모델 생성
#model=DecisionTreeClassifier()
#model=SVC()
model=KNeighborsClassifier()

### [4] 학습<==학습용 데이터 사용-----------------------

-모델 객체변수명.fit(학습용 데이터, 학습용 라벨)

In [174]:
model.fit(X_train,y_train)

KNeighborsClassifier()

### [5] 성능 평가 <==테스트 데이터 사용--------------------

- 모델객체변수명.score( 테스트 데이터, 테스트 라벨)
* 모델에 테스트 데이터를 입력 ==> 예측라벨<---->테스트 라벨

In [175]:
model.score(X_test,y_test)

c:\Users\y2kjd\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.9666666666666667

-성능평가 모듈 : sklearn.metrics

-성능평가 함수 : accuracy_score()

In [176]:
from sklearn.metrics import accuracy_score

In [177]:
# 테스트 데이터에 대란 예측값 추출 => 모델객체변수명.predict(테스트데이터)
y_pre=model.predict(X_test)

c:\Users\y2kjd\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [178]:
type(X_test), X_test.shape

(pandas.core.frame.DataFrame, (30, 4))

In [179]:
y_pre, len(y_pre)

(array([2, 2, 0, 0, 1, 2, 0, 0, 1, 2, 1, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 2,
        1, 0, 2, 1, 2, 2, 0, 2]),
 30)

In [180]:
# 정답비율
accuracy_score(y_test,y_pre)

0.9666666666666667

In [181]:
# 정답 갯수
accuracy_score(y_test,y_pre,normalize=False)

29

In [182]:
# 임의의 데이터 => [1.2, 3.2, 0.4, 2.9]
new_data=[1.2, 3.2, 0.4, 2.9]
model.predict([new_data, new_data])

c:\Users\y2kjd\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
c:\Users\y2kjd\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([0, 0])

In [183]:
import numpy as np

new_data=np.array([1.2, 3.2, 0.4, 2.9]).reshape(1,-1)
new_data.shape

(1, 4)

In [184]:
model.predict(new_data)

c:\Users\y2kjd\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
c:\Users\y2kjd\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([0])

In [1]:
import pycaret

In [2]:
import sklearn

In [3]:
import pandas

In [4]:
import numpy

In [5]:
import matplotlib